# Copyright (c) The New York Times Company

changesetIgnorePatterns:
  - "**/*.{test}.{js,ts,jsx,tsx}"
  - "!(.yarn/versions/**|src/**/*|package.json|.swcrc*)"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

nodeLinker: node-modules
