# Copyright (c) The New York Times Company

name: check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install corepack
        run: npm i -g corepack

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn check:lint

      - name: Format
        run: yarn check:format

      - name: Types
        run: yarn check:types

      - name: Version
        run:
          git fetch origin main --depth 1 && ./scripts/if-no-version-change.sh
          yarn version check

  bump-version:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      contents: write

    steps:
      - name: Check for version bump
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          ./scripts/if-version-change.sh git tag v${PACKAGE_VERSION}
          git push --tags

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install corepack
        run: npm i -g corepack

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test
